### ISSUE TITLE
last update (about 2pm on 09/22/2015) killed my app

### ISSUE THREAD

**Issue by ArgonCode** [raelgc/scudcloud#237]
1. I have Linux Mint 17.2 xfce
2. Menu icon does nothing
3. running `scudcloud` in terminal gives me this error trace:

```
Traceback (most recent call last):
  File "/opt/scudcloud/lib/speller.py", line 7, in <module>
    import hunspell
ImportError: No module named 'hunspell'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 11, in <module>
    from scudcloud import ScudCloud
  File "/opt/scudcloud/lib/scudcloud.py", line 7, in <module>
    from speller import Speller
  File "/opt/scudcloud/lib/speller.py", line 9, in <module>
    hunspell.HunSpell = None
NameError: name 'hunspell' is not defined
```
1. I found this: https://pypi.python.org/pypi/hunspell and installed python-dev and libhunspell-dev. I could not install hunspell.
2. I did some digging and got it installed with `pip install https://pypi.python.org/packages/source/h/hunspell/hunspell-0.3.3.tar.gz#md5=25ceaf642f16e623a857689b2323bd65` 
3. Still getting the same error as in point 3.

Hope that helps in fixing it.

**Comment by porjo** [comment]
Same for me on Fedora 22. Hunspell packages are installed:

```
$ sudo dnf list hunspell*
Installed Packages
hunspell.x86_64                                                                            1.3.3-5.fc22                                                                                 @System
hunspell-en.noarch                                                                         0.20140811.1-1.fc22                                                                          @System
hunspell-en-GB.noarch                                                                      0.20140811.1-1.fc22                                                                          @System
hunspell-en-US.noarch                                                                      0.20140811.1-1.fc22                                                                          @System
```

**Comment by mbajor** [comment]
@porjo Try to install gcc, python3-devel, hunspell-devel and then execute command:
sudo pip install hunspell

**Comment by raelgc** [comment]
Try install `python3-hunspell` package, if exists.

Anyway, the code is supposed to work without it. I'll work on fix right now.

**Comment by raelgc** [comment]
This issue was automatically closed by the commit message. Let me re-open in case more people report it.

**Comment by raelgc** [comment]
Guys, fixed in master. Sorry for the inconvenience.

**Comment by mbajor** [comment]
@raelgc Thx for fix. python3-hunspell (or simillar package) doesn't exists in standard openSUSE repositories.
@porjo Fedora and openSUSE repositories has been updated. Build in progress.

**Comment by raelgc** [comment]
@mbajor Thank you!

Indeed, I was searching in Fedora repos, there is only the `python2.7` version (`pyhunspell`).

**Comment by ArgonCode** [comment]
The second update you pushed, fixed it for me. thanks so much!
