### ISSUE TITLE
Error starting on fedora 22

### ISSUE THREAD

**Issue by dereke** [raelgc/scudcloud#242]
When I try to run `scudcloud` I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 11, in <module>
    from scudcloud import ScudCloud
  File "/opt/scudcloud/lib/scudcloud.py", line 25, in <module>
    class ScudCloud(QtGui.QMainWindow):
  File "/opt/scudcloud/lib/scudcloud.py", line 31, in ScudCloud
    speller = Speller()
  File "/opt/scudcloud/lib/speller.py", line 29, in __init__
    self.hunspell = hunspell.HunSpell(dictionaryPath + ".dic", dictionaryPath + ".aff")
hunspell.error: (2, 'No such file or directory')
```

**Comment by mbajor** [comment]
@dereke I've udpdated repository (Changed Requires to Suggests for libqt4-webkit-qupzillaplugins and python3-hunspell). Please, update scudcloud package and uninstall libqt4-webkit-qupzillaplugins and python3-hunspell.
I think #241 will fix this issue.

**Comment by dereke** [comment]
working now - thanks for the quick response!
