### ISSUE TITLE
PyQt4 errors from master

### ISSUE THREAD

**Issue by tedwardd** [raelgc/scudcloud#398]
Hello,

I've created a python 3.5.1 virtualenv inside of my clone of the scudcloud repository. While inside of the virtualenv I've downloaded the source for PyQt4 and SIP and built and installed those modules. If I run `from PyQt4 import QtCore` from the python console (for the virtualenv) I receive no errors, however, scudcloud does not seem to agree that PyQt4 is installed correctly. I get the following exception:

```
Traceback (most recent call last):
  File "/home/elw/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/elw/.pyenv/versions/3.5.1/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/elw/git-work/scudcloud/scudcloud/__main__.py", line 16, in <module>
    import scudcloud.scudcloud as sca
  File "/home/elw/git-work/scudcloud/scudcloud/scudcloud.py", line 1, in <module>
    from scudcloud.cookiejar import PersistentCookieJar
  File "/home/elw/git-work/scudcloud/scudcloud/cookiejar.py", line 3, in <module>
    class PersistentCookieJar(QtNetwork.QNetworkCookieJar):
AttributeError: module 'PyQt4.QtNetwork' has no attribute 'QNetworkCookieJar'
```

If I remove my .python-version file from the git directory and try `python3 -m scudcloud` everything seems to work fine which leads me to believe it's an issue with installing PyQt4 from source and my virtualenv.

I'm thinking this might be a little beyond the scope of your tool but I would appreciate any assistance you could provide in troubleshooting. I'm happy to provide any additional information that might help.

**Comment by tedwardd** [comment]
Oh, sorry, I also meant to say in the original post that python3 outside of the virtualenv is 3.4.3 and PyQt4 and SIP are installed from the the upstream package repositories, not source like in the virtualenv.
