### ISSUE TITLE
403 Errors for some (team) icons

### ISSUE THREAD

**Issue by jayme-github** [raelgc/scudcloud#442]
I get 403 errors for some (not all) team icons since today (kubernetes, google cloud platform, ...).

Debian Jessie (+Backports)
scudcloud 1.22-2

``` pytb
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scudcloud/wrapper.py", line 211, in populate
    file_name, headers = request.urlretrieve(data['icon'], icon_path)
  File "/usr/lib/python3.4/urllib/request.py", line 178, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by jayme-github** [comment]
Silently disappeared today. Maybe a temporary server or cookie issue?

Leaving this opened. Maybe someone want's to add an enhancement and show a default team icon instead of an empty box in case of HTTPError.

**Comment by ronrun** [comment]
I had a similar problem, and I just fixed it. I wanted to execute:
sudo add-apt-repository -y ppa:ondrej/php
Then I got those error message.

The problem was, I changed the ip address of my newly installed ubuntu, from dhcp to static 192.168.xx.xx, but I didn't set the dns address, which is: 
dns-nameservers 8.8.8.8

Maybe you need to set your nameserver.
