### ISSUE TITLE
scudcloud is hanging a lot today

### ISSUE THREAD

**Issue by shevek** [raelgc/scudcloud#451]
Mostly, it's blocking the entire GUI, and losing settings, and stuff, which is making it pretty unusable.

I get some of these:

```
SpellCheck: Language = "en_US" 
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1183, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1182, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1133, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 963, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 898, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1279, in connect
    super().connect()
  File "/usr/lib/python3.4/http/client.py", line 871, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 512, in create_connection
    raise err
  File "/usr/lib/python3.4/socket.py", line 503, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scudcloud/wrapper.py", line 215, in populate
    file_name, headers = request.urlretrieve(data['icon'], icon_path)
  File "/usr/lib/python3.4/urllib/request.py", line 186, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 464, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 482, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 442, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1226, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1185, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```

**Comment by raelgc** [comment]
Hi @shevek and thanks for raising this issue.

This line is the one trying the download the team icon to use in the left pane. The error is about a timeout while trying to read the icons.

Had you faced a slow connection or was under a proxy on that time?

**Comment by shevek** [comment]
I frequently have intermittent connections. That's just life. :-( It's a little difficult when all these downloads are sequential and block the GUI, though.

**Comment by raelgc** [comment]
Reminder to myself: use threads to download team icons, as seen on https://gist.github.com/JonasGroeger/3485298

**Comment by raelgc** [comment]
I changed the downloader to work in a non blocking way. Is this still an issue?
