### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by schnittchen** [raelgc/scudcloud#457]
## ScudCloud Version

`
/usr/lib/python3/dist-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python3/dist-packages/scudcloud/scudcloud.py:27: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, Dbusmenu
ScudCloud 1.22
Python 3.5.1+
Qt 4.8.7
PyQt 4.11.4
SIP 4.17
`
## Distro and Desktop info
- Distribution: Ubuntu 16.4 "xenial"
- Desktop environment: GNOME shell
## What happens

ScudCloud opens, shows a spinner on the Slack spash message, then hangs for a while, then shows a cached channel content, then hangs. Next up, the Ubuntu Crash Reporter opens.

I could not copy the exception message and traceback from the stupid Crash Reporter, but launching scudcloud from the console revealed the same:

```
  File "/usr/lib/python3.5/urllib/request.py", line 1243, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1260, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 376, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 748, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 984, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 629, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/scudcloud/wrapper.py", line 211, in populate
    file_name, headers = request.urlretrieve(data['icon'], icon_path)
  File "/usr/lib/python3.5/urllib/request.py", line 187, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1286, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1245, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:645)>
```

**Comment by raelgc** [comment]
Hi @schnittchen and thanks for spent your time reporting this issue!

Can you, please, tell me what is the output of the following command?

```
python3 -c "import ssl; print(ssl.OPENSSL_VERSION)"
```

Here is what I have under the same Ubuntu version (but using Unity):

```
OpenSSL 1.0.2g-fips  1 Mar 2016
```

**Comment by schnittchen** [comment]
Sure!

```
OpenSSL 1.0.2g-fips  1 Mar 2016
```

The problem btw has magically disappeared. What has changed since then:
1) my network was very flakey, and is stable now
2) I have upgraded nodejs by a patch level version

(2) is probebly unrelated to this...

**Comment by schnittchen** [comment]
This also means this bug is probably hard to reproduce... :(

**Comment by raelgc** [comment]
Well, we faced a similar issue due intermittent connection, #442.

Probably work on the fix for it (using threads to download the team icons) plus some try/catch around it, will prevent both.

**Comment by schnittchen** [comment]
You probably meant #451 ...

**Comment by raelgc** [comment]
Yes, thanks! #442 is just another improvement related to team icons, but not related to this issue specifically.

**Comment by ronrun** [comment]
I just answered in #442. My problem is that I forget to set the dns address
