### ISSUE TITLE
gir1.2-notify-0.7 is not in dependency list of QT5 version

### ISSUE THREAD

**Issue by Grief** [raelgc/scudcloud#489]
When installing scudcloud from yakkety ppa, it crashes with `ValueError: Namespace Notify not available` during the startup. The reason of the crash is that `gir1.2-notify-0.7` is not in the list of dependencies. After installing that package, application runs normally.

**Comment by raelgc** [comment]
Hi @Grief and thank you for reporting this!

Can you, please, investigate if `girl1.2-notify-0.7` is a replacement for `gir1.2-unity-5.0`? (The later was a requirement in 16.04).

**Comment by Grief** [comment]
@raelgc I don't think so:
1. I don't have unity at all, I use KDE, why should unity package be used then?
2. Installing this package doesn't fix that issue.
3. I guess, that `/usr/lib/girepository-1.0/Notify-0.7.typelib
` is required by `gi` python package and that file is contained in `gir1.2-notify-0.7` only:

```
Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 9, in <module>
    load_entry_point('scudcloud==1.32', 'gui_scripts', 'scudcloud')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2570, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2230, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2236, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/scudcloud/__main__.py", line 16, in <module>
    import scudcloud.scudcloud as sca
  File "/usr/lib/python3/dist-packages/scudcloud/scudcloud.py", line 3, in <module>
    from scudcloud.notifier import Notifier
  File "/usr/lib/python3/dist-packages/scudcloud/notifier.py", line 4, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Notify not available
```

```
wajig listfiles gir1.2-notify-0.7
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/gir1.2-notify-0.7
/usr/share/doc/gir1.2-notify-0.7/copyright
/usr/lib
/usr/lib/girepository-1.0
/usr/lib/girepository-1.0/Notify-0.7.typelib
/usr/share/doc/gir1.2-notify-0.7/AUTHORS
/usr/share/doc/gir1.2-notify-0.7/changelog.Debian.gz
/usr/share/doc/gir1.2-notify-0.7/NEWS.gz
```

**Comment by Grief** [comment]
@raelgc Sorry, just realized that I've understood you question wrong. But the answer is still no, these are different packages as far as I can see

**Comment by raelgc** [comment]
Thank you @Grief! :)
