### ISSUE TITLE
Can't Install on MX-60

### ISSUE THREAD

**Issue by ghost** [raelgc/scudcloud#525]
## Distro and Desktop info

  - Distribution: MX-60
  - Desktop environment: XFCE

## Expected behavior
Install

## Actual behavior
`sudo apt-add-repository -y ppa:rael-gc/scudcloud
WARNING:root:could not open file '/etc/apt/sources.list'

WARNING:root:could not open file '/etc/apt/sources.list'

Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for MX/Metamorphosis`

## Steps to reproduce
 1. `sudo apt-get update && sudo apt-get upgrade`
 2. `sudo apt-get install software-properties-common && sudo apt-get install lsb-release`
 3. `sudo apt-add-repository -y ppa:rael-gc/scudcloud`

**Comment by raelgc** [comment]
Can you, please, try steps described here? https://github.com/raelgc/scudcloud#debian-and-derivatives-like-bunsenlabs-linux

**Comment by ghost** [comment]
Just realized something. . .
What goes in `codename`?

Also, once I type #3, I get this:
` sudo apt-add-repository -y ppa:rael-gc/scudcloud
WARNING:root:could not open file '/etc/apt/sources.list'

WARNING:root:could not open file '/etc/apt/sources.list'

Traceback (most recent call last):
File "/usr/bin/apt-add-repository", line 167, in
sp = SoftwareProperties(options=options)
File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in init
self.reload_sourceslist()
File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
self.distro.get_sources(self.sourceslist)
File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
(self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for MX/Metamorphosis`
