### ISSUE TITLE
Not work on OpenSUSE Leap 42.2 

### ISSUE THREAD

**Issue by Akay7** [raelgc/scudcloud#531]
## ScudCloud Version
I'm try install that package from OpenSUSE repository
Output of `scudcloud --version`:
`/usr/lib/python3.4/site-packages/scudcloud/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.`
`  from gi.repository import Notify`
`ScudCloud 1.41`
`Python 3.4.5`
`Qt 4.8.6`
`PyQt 4.11.4`
`SIP 4.16.9`

I'm also tried install from source code after get that error, but it's not work too, error with import PyQt

## Distro and Desktop info

  - Distribution: OpenSUSE
  - Version/Release: Leap 42.2
  - Desktop environment: KDE

## Expected behavior
See chat

## Actual behavior
See infinite

## Steps to reproduce
 1. Login to team
 2. Loading never finished

**Comment by riflon** [comment]
Same issue here with Opensuse Leap 42.2. Are you planning to export the fix to all OS versions?

**Comment by raelgc** [comment]
Hi @riflon. Unfortunately I'm not responsible for openSUSE packages.

Anyway, the fix is simple: locate, edit file `scudcloud/__main__.py` and change:

```python
app.setApplicationName(Resources.APP_NAME+' Slack_SSB')
```

by this:

```python
app.setApplicationName(Resources.APP_NAME+' Slack')
```

**Comment by riflon** [comment]
Ohh perfect! thank you very much @raelgc .

Cheers!

**Comment by riflon** [comment]
Confirmed!!!! Scudcloud is running smoothly on my Opensuse.
Thanks again!

**Comment by raelgc** [comment]
Welcome! I'm glad to hear it worked!

**Comment by mbajor** [comment]
@Akay7 @riflon @raelgc I'm sorry. I overlooked the release. SUSE repositories has been updated to 1.43.

**Comment by Akay7** [comment]
@mbajor I'm try reinstall from repository and get that error, when start or scudcloud --version command, what I'm doing wrong?

```
Traceback (most recent call last):
  File "/usr/bin/scudcloud", line 9, in <module>
    load_entry_point('scudcloud==1.43', 'gui_scripts', 'scudcloud')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2681, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('gui_scripts', 'scudcloud') not found
```
